mmablog/urls.py
from django.urls import path
from .views import HomeView,ArticleView,ContactUsView,BlogView

app_name = 'mmablog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('news/<slug:slug>/', ArticleView.as_view(), name='article'),
    path('category/<str:category>/', BlogView.as_view(), name='categoryNews'),
    path('contact/', ContactUsView.as_view(), name='contact'),
    
]

mmablogproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mmablog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/footerbar/footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid bg-dark pt-5 px-sm-3 px-md-5 mt-5">
    <div class="row py-4">
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Get In Touch</h5>
            <!-- <p class="font-weight-medium"><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p> -->
            <!-- <p class="font-weight-medium"><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p> -->
            <p class="font-weight-medium"><i class="fa fa-envelope mr-2"></i>@MMA_master_1</p>
            <h6 class="mt-4 mb-3 text-white text-uppercase font-weight-bold">Follow Us</h6>
            <div class="d-flex justify-content-start">
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="https://www.twitter.com/@MMA_master_1"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" ><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" ><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" ><i class="fab fa-instagram"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square" ><i class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Popular News</h5>
            
            {% for blog in popular_blogs %}
                <div class="mb-3">
                    <div class="mb-2">
                        <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="{% url 'mmablog:categoryNews' blog.category.name %}">{{blog.category.name}}</a>
                        <a class="text-body" href=""><small>{{blog.posted_date}}</small></a>
                    </div>
                    <a class="small text-body text-uppercase font-weight-medium" href="{% url 'mmablog:article' blog.slug %}">{{blog.topic|truncatechars:'54'}}</a>
                </div>
            {% endfor %}
                
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Categories</h5>
            <div class="m-n1">
                
                {% for category in blog_category %}
                    <a href="{% url 'mmablog:categoryNews' category.name %}" class="btn btn-sm btn-secondary m-1">{{category.name}}</a>
                {% endfor %}
                    
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Flickr Photos</h5>
            <div class="row">
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-1.jpg' %}" alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-2.jpg' %}" alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-3.jpg' %}" alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-4.jpg' %}" alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-5.jpg' %}" alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-1.jpg' %}" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid py-4 px-sm-3 px-md-5" style="background: #111111;">
    <p class="m-0 text-center">&copy; <a href="#">MMA Master1</a>. All Rights Reserved.
    </p>
</div>
<!-- Footer End -->