mmablog/urls.py
from django.urls import path
from .views import HomeView,ArticleView,ContactUsView,BlogView

app_name = 'mmablog'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('news/<slug:slug>/', ArticleView.as_view(), name='article'),
    path('category/<str:category>/', BlogView.as_view(), name='categoryNews'),
    path('contact/', ContactUsView.as_view(), name='contact'),
    
]

mmablogproject/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mmablog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/headandnavbar/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">

    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    {% if page_name == 'home' %}
    <title>MMA Master 1 - N01 combat sport news website</title>
    <meta property="og:title" content="MMA Master 1 - N01 combat sport news website">
    <meta property="og:description" content="Home of all combart Sport News">
    
    <meta property="og:image" content="{% static 'img/mmamaster1.jpg' %}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{request.get_host}}{% static 'img/mmamaster1.jpg' %}">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:site" content="@MMA_master_1">
    <meta property="twitter:title" content="MMA Master 1 - N01 combat sport news website">
    <meta property="twitter:description" content="Home of all combart Sport News">
    <meta property="twitter:image" content="{{request.get_host}}{% static 'img/mmamaster1.jpg' %}">



    {% elif page_name == 'article' %}

    <title>{{blog.topic}} - MMA master1</title>
    <meta property="og:title" content="{{blog.topic}} - MMA master1">
    <meta property="og:description" content="{{blog.article|linebreaksbr}}">
    <meta property="og:image" content="{{request.get_host}}{{blog.topic_image.url}}">
    <meta property="og:type" content="{{request.get_host}}">
    <meta property="og:url" content="{{request.path}}">
    <meta property="twitter:card" content="{{request.get_host}}{{blog.topic_image.url}}">
    <meta property="twitter:site" content="@MMA_master_1">
    <meta property="twitter:title" content="{{blog.topic}} - MMA master1">
    <meta property="twitter:description" content="{{blog.article|linebreaksbr}}">
    <meta property="twitter:image" content="{{request.get_host}}{{blog.topic_image.url}}">
    {% else %}
    <title>MMA Master 1 - {{category}} News</title>
    <meta property="og:title" content="MMA Master 1 - {{category}} News">
    <meta property="og:description" content="{{category}} News, Breaking New, what's happening">

    <meta property="og:image" content="{{request.get_host}}{% static 'img/mmamaster1.jpg' %}">
    <meta property="og:type" content="{{request.get_host}}">
    <meta property="og:url" content="{{request.path}}">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:site" content="@MMA_master_1">
    <meta property="twitter:title" content="{{category}} Breaking News">
    <meta property="twitter:description" content="{{category}} News, Breaking New, what's happening">
    <meta property="twitter:image" content="{{request.get_host}}{% static 'img/mmamaster1.jpg' %}">
    {% endif %}


    <!-- Favicon -->
    <link href="{% static 'img/mmamaster1.jpg' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <!-- <div class="row align-items-center bg-dark px-lg-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-n2">
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#">Monday, January 1, 2045</a>
                        </li>
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#">Advertise</a>
                        </li>
                        <li class="nav-item border-right border-secondary">
                            <a class="nav-link text-body small" href="#">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body small" href="#">Login</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 text-right d-none d-md-block">
                <nav class="navbar navbar-expand-sm bg-dark p-0">
                    <ul class="navbar-nav ml-auto mr-n2">
                        <li class="nav-item">
                            <a class="nav-link text-body" href="#"><small class="fab fa-twitter"></small></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body" href="#"><small class="fab fa-facebook-f"></small></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body" href="#"><small class="fab fa-linkedin-in"></small></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body" href="#"><small class="fab fa-instagram"></small></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body" href="#"><small class="fab fa-google-plus-g"></small></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-body" href="#"><small class="fab fa-youtube"></small></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div> -->
        <div class="row align-items-center bg-white py-3 px-lg-5">
            <div class="col-lg-4">
                <a href="index.html" class="navbar-brand p-0 d-none d-lg-block">
                    <h1 class="m-0 display-4 text-uppercase text-primary">MMA<span
                            class="text-secondary font-weight-normal">Master1</span></h1>
                </a>
            </div>
            <div class="col-lg-8 text-center text-lg-right">
                <a href="https://htmlcodex.com"><img class="img-fluid" src="img/ads-728x90.png" alt=""></a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

    {% include 'headandnavbar/navbar.html' %}

    
    {% block content %}
        
    {% endblock content %}
    {% include 'footerbar/footer.html' %}
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-square back-to-top"><i class="fa fa-arrow-up"></i></a>
            <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/headandnavbar/navbar.html
<div class="container-fluid p-0">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
        <a href="{% url 'mmablog:home' %}" class="navbar-brand d-block d-lg-none">
            <h1 class="m-0 display-4 text-uppercase text-primary">MMA<span
                    class="text-white font-weight-normal">Master1</span></h1>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
            <div class="navbar-nav mr-auto py-0">
                <a href="{% url 'mmablog:home' %}" class="nav-item nav-link {% if page_name == 'home' %} active  {% endif %}">Home</a>
                
                {% for category in popular_blog_category|slice:"3" %}
                    <a href="{% url 'mmablog:categoryNews' category.name %}" class="nav-item nav-link {% if page_name == category.name %} active  {% endif %}">{{category.name}}</a>
                {% endfor %}
                    
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle " data-toggle="dropdown">More</a>
                    <div class="dropdown-menu rounded-0 m-0">
                        
                        {% for category in popular_blog_category %}
                            <a href="{% url 'mmablog:categoryNews' category.name %}" class="dropdown-item {% if page_name == category.name %} active  {% endif %}">{{category.name}}</a>
                        {% endfor %}
                            
                        
                    </div>
                </div>
                <!-- <a href='' class="nav-item nav-link">Single News</a> -->
                <a href='{% url "mmablog:contact" %}' class="nav-item nav-link {% if page_name == 'contact' %} active  {% endif %}">Contact</a>
            </div>
            <div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
                <input type="text" class="form-control border-0" placeholder="Keyword">
                <div class="input-group-append">
                    <button class="input-group-text bg-primary text-dark border-0 px-3"><i
                            class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </nav>
</div>